# Generated by Django 4.2.6 on 2023-11-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='код верификации email'),
        ),
    ]
