# Generated by Django 4.2.6 on 2023-11-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_active',
        ),
    ]
