# Generated by Django 4.2.6 on 2023-11-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_version_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='активная версия'),
        ),
    ]
