# Generated by Django 4.2.6 on 2023-11-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'активная'), (False, 'не активная')], verbose_name='активная версия'),
        ),
    ]
