# Generated by Django 4.2.6 on 2023-11-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_version_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ('product',), 'verbose_name': 'версия', 'verbose_name_plural': 'версии'},
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='only_one_active_version_for_product'),
        ),
    ]
