# Generated by Django 4.2.6 on 2023-11-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_version_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='version',
            name='only_one_active_version_for_product',
        ),
    ]
